# -*- coding: utf-8 -*-
"""lab5ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-giZB9lG8K91jVPFyMXT3XDqv7TmuLde
"""

from google.colab import files
uploaded = files.upload()

import json

with open('schacon.repos.json', 'r') as file:
    data = json.load(file)

repositories = []

for repo in data[:5]:  # Only taking the first 5 repositories
    name = repo['name']
    html_url = repo['html_url']
    updated_at = repo['updated_at']
    visibility = repo['visibility']

    repositories.append([name, html_url, updated_at, visibility])

# Check the first few entries to ensure correctness
repositories

import pandas as pd

# Create DataFrame
df = pd.DataFrame(repositories, columns=['name', 'html_url', 'updated_at', 'visibility'])

# Display DataFrame to confirm
df.head()

df.head().to_csv('chacon.csv', index=False)
files.download('chacon.csv')